server:
  port: 9090

spring.datasource:
  url: jdbc:postgresql://localhost:5432/deeproute?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  username: postgres
  password: 123456
  driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.deeproute.Model



spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10240MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  data:
    redis:
      timeout: 10000

